### ISSUE TITLE
Implement ZFS encryption support when available

### ISSUE THREAD

**Issue by hbos** [ossobv/planb#14]
https://github.com/zfsonlinux/zfs/commit/b52563034230b35f0562b6f40ad1a00f02bd9a05

should be coming up in the next release. 

Bonus points if the encryption keys can be stored outside planb (service/servers). (e.g. https://www.vaultproject.io/ or similar)

**Comment by vilitux** [comment]
Merged in https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.8.0-rc1

**Comment by hbos** [comment]
On June 13th 2019 ZoL 0.8.1 was released.
Which means we can move forward with further implementation. @wdoekes

**Comment by wdoekes** [comment]
Mostly working: f3227ca979b8b8e89af9219f2f4c1714037442d6
