### ISSUE TITLE
When cleaning up old monthlies, keep 'm by count, not by date

### ISSUE THREAD

**Issue by wdoekes** [ossobv/planb#16]
Just now, I restarted a backup and amazingly, all old snapshots were pruned immediately, leaving me with only todays backup.

It should've kept 3 monthlies, because it's set to 3. Not purge every old one just because they're older than three months old.

**Comment by wdoekes** [comment]
@Urth : can you describe what happens in this scenario now?

Will it keep 5 months old snaps, but drop 7 month old ones? Because 5 is closer to 3?

**Comment by Urth** [comment]
Snapshots are still kept by date, relative to the latest snapshot, rather than count.
Backups older than the retention count relative to the latest snapshot will be destroyed!
