### ISSUE TITLE
Got stale dutree lock after reboot

### ISSUE THREAD

**Issue by wdoekes** [ossobv/planb#32]
We should detect this stale dutree lock somehow. Now all backups stalled on this.

Also, we should consider doing the dutree'ing in a separate job (we can do it on the RO .zfs filesystems).

Additionally, we want to disable the dutree for some filesets, like large swift ones.

**Comment by Urth** [comment]
Dutree can be disabled on a per fileset basis and now runs on a separate task queue.
https://github.com/ossobv/planb/compare/244e928..f5556bd
