### ISSUE TITLE
Moderate vuln in django >= 2.2.0, < 2.2.

### ISSUE THREAD

**Issue by wdoekes** [ossobv/planb#33]

**Comment by Urth** [comment]
Fixed in 38239e2a9dd3aab5fbc0afb15fff44193a863ac4 and 9ac7f3b476e82ad7cbcf0e7f8277c759fc652824

**Comment by Urth** [comment]
Note: Users still need to force the update to Django>=2.2.8 themselves but PlanB no longer depends on Django<2.2.
