### ISSUE TITLE
Missing renderer=None in multi_email_field...Widget.render()

### ISSUE THREAD

**Issue by wdoekes** [ossobv/planb#34]
Needs manual patch atm..

**Comment by Urth** [comment]
The requirements.txt and setup.py have been changed to point to https://github.com/ossobv/django-multi-email-field which is a fork with a working patch. There is a pull request but so far there has not been a new release.

https://github.com/fle/django-multi-email-field/pull/10

**Comment by Urth** [comment]
Fixed in 42ecc5eae013271e8f0a09912ac58277674e242f
